### ISSUE TITLE
Incorrect Maximized window size when use NCButtons, crop system and NC buttons

### ISSUE THREAD

**Issue by RicardoBer** [RRUZ/vcl-styles-utils#175]
![d97aa1e0-b960-11e5-841b-25ff4c6b88bc](https://cloud.githubusercontent.com/assets/14173576/12406458/75e0a14c-be4d-11e5-9e78-1bd186f86016.jpg)

When add NCButtons to Form Title area the window scales wrong on maximize state (more big than correct one) and crop the buttons on title area and border.

It is tested on:

-Delphi XE2, XE7 update 1
-Windows: Works ok on XP and windows 7 32 & 64 bits unthemed. Fails on Windows 7 32 & 64bits whit aero an themed.
-Code demo for test, unmodified "Vcl Styles Utils NC (Demo App)" included with vcl-styles-utils
-vcl-styles-utils, latest available on github on January 19 of 2015

**Comment by RRUZ** [comment]
Please check which you are using the last version of the sources (also check the paths of the library). Because this issue was fixed.

Check this sample image of  a maximized window.

![2016-01-18 23_23_16-sample nc buttons](https://cloud.githubusercontent.com/assets/11446959/12407948/a1621872-be3a-11e5-81f6-48a5c7dbf548.png)

**Comment by RicardoBer** [comment]
Yes, I download the master zip from github just now, remove previous folders and library paths an create again. The problem persists, I you told that It works on latest version, I believe you of course, the only thing that I can suspect it's that the delphi installation or XE7 has the blame.

I will try to uninstall this one and install other delphi version for test I think we bougth XE8 too.

**Comment by RRUZ** [comment]
You don't need install Delphi again. Just check which the source of the *VCL Styles Utils* includes the changes of the last commit https://github.com/RRUZ/vcl-styles-utils/commit/db81ceb18301abdc76495380b9ef0e73d90f5975

**Comment by RicardoBer** [comment]
Ok, seems that is few hour repaired, it show committed 10 hours ago, I downloaded again and now work as expected, many, many thanks.

**Comment by RRUZ** [comment]
No problem.
