### ISSUE TITLE
Issues in the Style of TaskDialog when the (tfRTLLayout) Flag is set to True

### ISSUE THREAD

**Issue by khaliddawood** [RRUZ/vcl-styles-utils#271]
The following is the issues raised when the  (tfRTLLayout) Flag is set to True for the TaskDialog:
1) Text in the Title Bar is mirrored 
2) The mouse position of close button in the title bar is not in the correct position
3) Incorrect paint of Button   

The picture on the following link demonstrate the above mentioned issues:

https://app.box.com/s/0kq1frb7gbrjlzqvnqrd05ddi8nrk5jh

**Comment by rickard67** [comment]
I think I've fixed it. I would be very happy if you tried it https://github.com/rickard67/vcl-styles-utils

The fix is added to the latest pull request, so lets make sure it works properly...

/Rickard

**Comment by khaliddawood** [comment]
Thanks Rickard,

The fix is working except one thing, the Command Link Button still not fixed, please see the picture in the below link:

https://app.box.com/s/1g8emb68n8ug2d01obguqpng9v74gebi

**Comment by rickard67** [comment]
Fixed https://github.com/rickard67/vcl-styles-utils. Thank you for testing.

/Rickard

**Comment by khaliddawood** [comment]
Thanks 
It is fixed, but there is an issue with Command Link Button and it is not related to the RightToLeft Layout, the space between the left border and the Command Link Button is not equal to the space between the right border and the Command Link Button, please see the picture in the below link:

https://app.box.com/s/u7gq0p16n79anhimz0r5v4ztejmdd2ck

**Comment by khaliddawood** [comment]
And one more thing, since you have solved the RightToLeft mirroring issue for the Dialogs, can you help us fixing this issue for the normal form. When we use the WS_EX_LAYOUTRTL flag we face the same issues:
1. Text in the Title Bar is mirrored
2. The mouse position for the title bar buttons not in the correct position

See the following picture:

https://app.box.com/s/rr3xrxse71p0txjgql5s75qlewas4w5x

Thanks & Regards,

Khalid Dawood

**Comment by rickard67** [comment]
VCL styles may have thicker window borders than Windows. In Windows 10 the border width is only 1 pixel, while a VCL style may use a border width of 7 pixels. And since the window size is not changed that means controls are slightly shifted to the right. You can see this in a few other shell dialog windows as well. I might look into it one day when I have time....

My interest in the VCL styles Utils components is just to theme shell dialogs and possibly fix some issues. I'm not going to fix other VCL style issues. You really should ask Embarcadero to fix these. It would benefit all of us if they did.

**Comment by khaliddawood** [comment]
Thank you Rickard for your great contribution to **VCL styles Utils**. In regards to the boarder issue, I believe the "VCL styles Utils" did fixed this issue for the normal form but not the dialog, therefore I think we can apply the same fix for the dialog.

Best Regards,

/Khalid

**Comment by rickard67** [comment]
Thanks,
I've fixed the TaskDialog size issue https://github.com/rickard67/vcl-styles-utils. Some other system dialogs should look better as well (like the color dialog).

/Rickard

**Comment by khaliddawood** [comment]
Thank you Rickard,

The fix is working and perfect.

Thank you for your great effort in fixing the Dialogs issues.

/Khalid
